using System;
using System.Linq;

namespace ProjectEuler
{
    class MainMenu
    {
        public MainMenu(string input)
        {
        }

        public bool Menu(string input)
        {
            Console.Clear();
            Console.WriteLine("Thank you " + input + ". The following problems are from Project Euleur. Please choose one:");

            Console.WriteLine(" ");

            Problem[] problems = new[] {
                new Problem {},
                new MultipleOf3And5             {Number = 01, Name = "Multiples of 3 and 5",         Description = "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. \nThe sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000."},
                new EvenFibonacci               {Number = 02, Name = "Even Fibanacci Numbers",       Description = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. \nBy starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  \nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, \nfind the sum of the even-valued terms."},
                new LargestPrime                {Number = 03, Name = "Largest Prime Number",         Description = "The prime factors of 13195 are 5, 7, 13 and 29. \nWhat is the largest prime factor of the number 600851475143?"},
                new LargestPalindrome           {Number = 04, Name = "Largest Palindrome Product",   Description = "A palindromic number reads the same both ways. \nThe largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. \nFind the largest palindrome made from the product of two 3-digit numbers."},
                new SmallestMultiple            {Number = 05, Name = "Smallest Multiple",            Description = "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. \nWhat is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"},
                new SumSquareDifference         {Number = 06, Name = "Sum Square Difference",        Description = "The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + ... + 10^2 = 385. \nThe square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)^2 = 55^2 = 3025. \nHence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640. \nFind the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."},
                new TenThousandAndFirstPrime    {Number = 07, Name = "10001st Prime",                Description = "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. \nWhat is the 10 001st prime number?"},
                new LargestInASeries            {Number = 08, Name = "Largest Product in a Series",  Description = "The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. \n Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. \n What is the value of this product?"},
                new SpecialPythagorean          {Number = 09, Name = "Largest Pythagorean Triplet",  Description = "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which: a^2 + b^2 = c^2 \n For example, 32 + 42 = 9 + 16 = 25 = 52. \n There exists exactly one Pythagorean triplet for which a + b + c = 1000. \n Find the product abc."},
                new SummationOfPrimes           {Number = 10, Name = "Summation of Primes",          Description = "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. \n Find the sum of all the primes below two million."},
                new LargestProductInAGrid       {Number = 11, Name = "Largest Product in a Grid",    Description = "https://projecteuler.net/problem=11"},
                new HighlyDivisibleNumber       {Number = 12, Name = "Highly Divisible Number",      Description = "https://projecteuler.net/problem=12"},
                new LargeSum                    {Number = 13, Name = "Large Sum",                    Description = "https://projecteuler.net/problem=13"},
                new LongestCollatzSequence      {Number = 14, Name = "Longest Collatz Sequence",     Description = "https://projecteuler.net/problem=14"},
                new LatticePaths                {Number = 15, Name = "Lattice Paths",                Description = "https://projecteuler.net/problem=15"},
                new PowerDigitSum               {Number = 16, Name = "Power Digit Sum",              Description = "https://projecteuler.net/problem=16"},
                new NumberLetterSum             {Number = 17, Name = "Number Letter Counts",         Description = "https://projecteuler.net/problem=17"},
                new MaxPathSumOne               {Number = 18, Name = "Maximum Path Sum 1",           Description = "https://projecteuler.net/problem=18"},
                new CountingSundays             {Number = 19, Name = "Counting Sundays",             Description = "https://projecteuler.net/problem=19"},
                new FactorialDigitSum           {Number = 20, Name = "Factorial Digit Sum",          Description = "https://projecteuler.net/problem=20"},
                new AmicableNumbers             {Number = 21, Name = "Amicable Numbers",             Description = "https://projecteuler.net/problem=21"},
                new NamesScores                 {Number = 22, Name = "Names Scores",                 Description = "https://projecteuler.net/problem=22"},
                new NonAbundantSums             {Number = 23, Name = "Non-abundant Sums",            Description = "https://projecteuler.net/problem=23"},
                new LexicographicPermutations   {Number = 24, Name = "Lexicographic Permutations",   Description = "https://projecteuler.net/problem=24"},
                new ThousandDigitFibNumber      {Number = 25, Name = "1000-digit Fibonacci number",  Description = "https://projecteuler.net/problem=25"}
            };

            foreach (var problem in problems.Skip(1))
                problem.ShowMenu();
            Console.WriteLine("Esc: Exit");
            Console.WriteLine("\nChoose from the above options:");

            int caseNumber = int.Parse(Console.ReadLine());

            switch (caseNumber)
            {
                case int n when (n > 0 && n < 26):
                    var selectedProblem = problems[n];
                    selectedProblem.ShowDescription();
                    selectedProblem.ShowAnswer();
                    break;

                default:
                    return true;
            }
            
            return true;
        }
    }
}
